-- Create the articles table
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  category TEXT,
  author TEXT,
  image_url TEXT,
  images TEXT[], -- Array of image URLs
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) is recommended but optional for initial dev if you want public read
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows everyone to read articles
CREATE POLICY "Public articles are viewable by everyone" ON articles
FOR SELECT USING (true);

-- Create a policy that allows authenticated users to insert articles (or everyone for dev)
CREATE POLICY "Enable insert for authenticated users only" ON articles
FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Also allow update for authors? For now simpler:
CREATE POLICY "Enable update for authenticated users only" ON articles
FOR UPDATE USING (auth.role() = 'authenticated');

-- STORAGE BUCKET SETUP (This usually needs to be done in dashboard, but policies can be SQL)
-- Ensure 'articles' bucket exists (You must do this in Supabase Dashboard -> Storage)
-- Value below is policy for storage objects
-- insert into storage.buckets (id, name, public) values ('articles', 'articles', true);
